### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [dmontoya1600/group-project-12#6]
Hello! 

I am reviewing all groups wikis today and wanted to drop a few things here that I would like y'all to take care of.

## General
- [x] Your home wiki page links to the example wiki page. Update those links to send me to your own wiki page. You do not want recruiters finding that!!

## MVP Feature List
- [x] Bonus > Search Feature: Remove the "(if possible)"

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by JoeZhang229** [comment]
Updated Wiki links

**Comment by dmontoya1600** [comment]
Updated "(if possible)"
